#Requires -Version 5.1
<#
.SYNOPSIS
  Self-host Langfuse for Mach2 and write mach2-config.env at repo root.
#>
param(
    [string]$LangfuseHost = "http://localhost:3000",
    [string]$OrgId = "mach2",
    [string]$OrgName = "Mach2",
    [string]$ProjectId = "mach2-dev",
    [string]$ProjectName = "mach2-dev",
    [string]$AdminEmail = "admin@mach2.local",
    [string]$AdminName = "Mach2 Admin"
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path (Join-Path $ScriptDir "..\..")
$RuntimeDir = Join-Path $ScriptDir "runtime"
$ConfigOut = Join-Path $RepoRoot "mach2-config.env"
$EnvFile = Join-Path $ScriptDir ".env.langfuse"

function New-HexSecret([int]$Bytes = 32) {
    $buf = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    return ([BitConverter]::ToString($buf) -replace '-', '').ToLower()
}

function New-LangfuseKey([string]$Prefix) {
    return "$Prefix$(New-HexSecret 16)"
}

function Test-Command([string]$Name) {
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

Write-Host "==> Mach2 Langfuse setup" -ForegroundColor Cyan
Write-Host "    Repo root: $RepoRoot"

if (-not (Test-Command docker)) {
    throw "Docker not found. Install Docker Desktop and ensure it is running."
}

$dockerInfo = docker info 2>&1
if ($LASTEXITCODE -ne 0) {
    throw "Docker daemon not running. Start Docker Desktop and retry."
}

# --- Generate secrets (skip if .env.langfuse exists and -ReuseEnv not needed) ---
$reuse = Test-Path $EnvFile
if ($reuse) {
    Write-Host "==> Reusing existing $EnvFile"
    Get-Content $EnvFile | ForEach-Object {
        if ($_ -match '^\s*([^#=]+)=(.*)$') {
            Set-Variable -Name $matches[1].Trim() -Value $matches[2].Trim() -Scope Script
        }
    }
} else {
    Write-Host "==> Generating secrets..."
    $NEXTAUTH_SECRET = New-HexSecret 32
    $SALT = New-HexSecret 16
    $ENCRYPTION_KEY = New-HexSecret 32
    $POSTGRES_PASSWORD = New-HexSecret 16
    $CLICKHOUSE_PASSWORD = New-HexSecret 16
    $REDIS_AUTH = New-HexSecret 16
    $MINIO_ROOT_PASSWORD = New-HexSecret 16
    $MINIO_SECRET = $MINIO_ROOT_PASSWORD
    $LANGFUSE_INIT_USER_PASSWORD = New-HexSecret 12
    $LANGFUSE_INIT_PROJECT_PUBLIC_KEY = New-LangfuseKey "pk-lf-"
    $LANGFUSE_INIT_PROJECT_SECRET_KEY = New-LangfuseKey "sk-lf-"
}

# --- Clone Langfuse upstream ---
if (-not (Test-Path (Join-Path $RuntimeDir "docker-compose.yml"))) {
    Write-Host "==> Cloning langfuse/langfuse into runtime/ ..."
    if (Test-Path $RuntimeDir) { Remove-Item $RuntimeDir -Recurse -Force }
    git clone --depth 1 https://github.com/langfuse/langfuse.git $RuntimeDir
    if ($LASTEXITCODE -ne 0) { throw "git clone failed" }
} else {
    Write-Host "==> Using existing runtime/ (langfuse clone)"
}

# --- Write docker .env ---
if (-not $reuse) {
    @"
# Generated by setup-scripts/langfuse/setup.ps1 — Docker Compose only
NEXTAUTH_URL=$LangfuseHost
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
SALT=$SALT
ENCRYPTION_KEY=$ENCRYPTION_KEY
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgresql://postgres:$POSTGRES_PASSWORD@postgres:5432/postgres
DIRECT_URL=postgresql://postgres:$POSTGRES_PASSWORD@postgres:5432/postgres
CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD
REDIS_AUTH=$REDIS_AUTH
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=$MINIO_SECRET
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=$MINIO_SECRET
LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=$MINIO_SECRET
TELEMETRY_ENABLED=false
LANGFUSE_INIT_ORG_ID=$OrgId
LANGFUSE_INIT_ORG_NAME=$OrgName
LANGFUSE_INIT_PROJECT_ID=$ProjectId
LANGFUSE_INIT_PROJECT_NAME=$ProjectName
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=$LANGFUSE_INIT_PROJECT_PUBLIC_KEY
LANGFUSE_INIT_PROJECT_SECRET_KEY=$LANGFUSE_INIT_PROJECT_SECRET_KEY
LANGFUSE_INIT_USER_EMAIL=$AdminEmail
LANGFUSE_INIT_USER_NAME=$AdminName
LANGFUSE_INIT_USER_PASSWORD=$LANGFUSE_INIT_USER_PASSWORD
"@ | Set-Content -Path $EnvFile -Encoding UTF8
    Write-Host "==> Wrote $EnvFile"
}

# --- Start stack ---
Write-Host "==> Starting Langfuse (docker compose up -d)..."
Push-Location $RuntimeDir
docker compose --env-file $EnvFile up -d
if ($LASTEXITCODE -ne 0) { Pop-Location; throw "docker compose up failed" }
Pop-Location

# --- Wait for health ---
Write-Host "==> Waiting for Langfuse at $LangfuseHost (up to 5 min)..."
$healthUrl = "$LangfuseHost/api/public/health"
$ready = $false
for ($i = 0; $i -lt 60; $i++) {
    try {
        $r = Invoke-WebRequest -Uri $healthUrl -UseBasicParsing -TimeoutSec 5
        if ($r.StatusCode -eq 200) { $ready = $true; break }
    } catch { }
    Start-Sleep -Seconds 5
    Write-Host "    ... still starting ($($i + 1)/60)"
}
if (-not $ready) {
    Write-Warning "Health check timed out. Langfuse may still be starting — check: docker compose -f $RuntimeDir/docker-compose.yml logs langfuse-web"
}

# --- Load keys from env file for output ---
$envMap = @{}
Get-Content $EnvFile | ForEach-Object {
    if ($_ -match '^\s*([^#=]+)=(.*)$') { $envMap[$matches[1].Trim()] = $matches[2].Trim() }
}

$generatedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

@(
"# ============================================================================="
"# Mach2 — generated configuration (DO NOT COMMIT)"
"# Generated: $generatedAt"
"# Generator: setup-scripts/langfuse/setup.ps1"
"# ============================================================================="
""
"# --- Langfuse (self-hosted observability) -----------------------------------"
"LANGFUSE_HOST=$LangfuseHost"
"LANGFUSE_PUBLIC_KEY=$($envMap['LANGFUSE_INIT_PROJECT_PUBLIC_KEY'])"
"LANGFUSE_SECRET_KEY=$($envMap['LANGFUSE_INIT_PROJECT_SECRET_KEY'])"
"LANGFUSE_PROJECT=$ProjectName"
"LANGFUSE_ORG_ID=$OrgId"
"LANGFUSE_PROJECT_ID=$ProjectId"
"OBSERVABILITY=langfuse"
""
"# Langfuse UI login (headless-init)"
"LANGFUSE_UI_URL=$LangfuseHost"
"LANGFUSE_UI_EMAIL=$($envMap['LANGFUSE_INIT_USER_EMAIL'])"
"LANGFUSE_UI_PASSWORD=$($envMap['LANGFUSE_INIT_USER_PASSWORD'])"
""
"# --- Ollama (local LLM + embeddings) ----------------------------------------"
"OLLAMA_BASE_URL=http://localhost:11434"
"OLLAMA_MODEL=gemma4:latest"
"OLLAMA_EMBEDDING_MODEL=nomic-embed-text"
""
"# --- ChromaDB (vector / shared memory) --------------------------------------"
"CHROMA_HOST=localhost"
"CHROMA_PORT=8000"
"CHROMA_PERSIST_DIR=./data/chroma"
"CHROMA_COLLECTION=mach2_shared"
""
"# --- FastAPI (harness API server) -------------------------------------------"
"MACH2_HOST=0.0.0.0"
"MACH2_PORT=8000"
"MACH2_RELOAD=true"
"MACH2_CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173"
"MACH2_DEBUG=false"
""
"# --- Agent runtime limits ---------------------------------------------------"
"MACH2_MAX_REACT_STEPS=10"
"MACH2_SCOUT_MAX_CONCURRENT=3"
"MACH2_CRITIQUE_MAX_ROUNDS=3"
""
"# --- General ----------------------------------------------------------------"
"ENV=development"
"LOG_LEVEL=INFO"
""
"# --- Docker stack secrets (for compose maintenance) -------------------------"
"# NEXTAUTH_SECRET=$($envMap['NEXTAUTH_SECRET'])"
"# POSTGRES_PASSWORD=$($envMap['POSTGRES_PASSWORD'])"
"# Runtime dir: setup-scripts/langfuse/runtime"
) | Set-Content -Path $ConfigOut -Encoding UTF8

Write-Host ""
Write-Host "==> Done!" -ForegroundColor Green
Write-Host "    Config file : $ConfigOut"
Write-Host "    Langfuse UI : $LangfuseHost"
Write-Host "    Login email : $($envMap['LANGFUSE_INIT_USER_EMAIL'])"
Write-Host "    Login pass  : $($envMap['LANGFUSE_INIT_USER_PASSWORD'])"
Write-Host "    Public key  : $($envMap['LANGFUSE_INIT_PROJECT_PUBLIC_KEY'])"
Write-Host ""
Write-Host "Next: copy mach2-config.env to .env (or merge) before Phase 1 coding."
